apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: stream-git-source
spec:
  type: git
  params: 
  - name: url
    value: https://github.com/kameshsampath/traffic-controller
  - name: revision
    value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: traffic-controller-image
spec:
  type: image
  params: 
  - name: url
    # if you are minikube uncomment this line
    #value: "dev.local/rhdevelopers/traffic-controller"
    # if you are on OpenShift uncomment the line below
    value: "image-registry.openshift-image-registry.svc:5000/tutorial/traffic-controller"