apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: stream-greeter-svc-deploy
spec:
  params:
  - name: mavenMirrorUrl
    description: the maven mirror
    default: http://repo1.maven.apache.org/maven2
  - name: kubernetesResourceFile
    description: the kubernetes resource file to apply
    default: app.yaml
  - name: contextDir
    description: the context directory of the sources
    default: .
  resources: 
  - name: appSource
    type: git
  - name: appImage
    type: image
  tasks: 
   - name: build-java-app
     taskRef:
       name: build-app
     params:
      - name: contextDir
        value: "$(params.contextDir)"
      - name: mavenMirrorUrl
        value: "$(params.mavenMirrorUrl)"
     resources:
      inputs:
        - name: source
          resource: appSource
      outputs:
        - name: builtImage
          resource: appImage
   - name: 
     taskRef:
       name: clients
     runAfter:
      - build-java-app
     resources:
      inputs:
        - name: source
          resource: appSource
        - name: image
          resource: appImage
          from: 
           - build-java-app
     params:
      - name: ARGS
        value:
        - "-c"
        - >
          yq 
          w 
          -d1 
          $(params.contextDir)/kubernetes/app.yaml 
          spec.template.spec.containers[0].image 
          $(inputs.resources.image.url) | kubectl apply -f -
       